### ISSUE TITLE
Support for setting icon size

### ISSUE THREAD

**Issue by bwmarrin** [bmcorser/fontawesome-markdown#6]
It would be wonderful if support could be added for setting the icon size, something that would replicated the below example.

```
<i class="fa fa-camera-retro fa-lg"></i> fa-lg
<i class="fa fa-camera-retro fa-2x"></i> fa-2x
<i class="fa fa-camera-retro fa-3x"></i> fa-3x
<i class="fa fa-camera-retro fa-4x"></i> fa-4x
<i class="fa fa-camera-retro fa-5x"></i> fa-5x
```

**Comment by bmcorser** [comment]
Sounds like an easy addition. How would you imagine the "shortcode" might look?
Perhaps one of:
 - `:fa-coffee fa-5x:`
 - `:fa-coffee 5x:`
 - `:fa-coffee 5:`

Can you point me to some documentation from FontAwesome explaining how they deal with icon size?

**Comment by bwmarrin** [comment]
Yikes, I just realized I missed your response.  I feel bad about that!

Here's a page from FontAwesome's site that shows an example of the sizes
http://fontawesome.io/examples/

Here's an example from that page :)

```html
<i class="fa fa-camera-retro fa-lg"></i> fa-lg
<i class="fa fa-camera-retro fa-2x"></i> fa-2x
<i class="fa fa-camera-retro fa-3x"></i> fa-3x
<i class="fa fa-camera-retro fa-4x"></i> fa-4x
<i class="fa fa-camera-retro fa-5x"></i> fa-5x
```

So following that style would probably make the most sense. :fa-coffee fa-2x: while not the most concise would probably be the most familiar.

Also, just fyi, here's an example of using your extension mixed with MkDocs, http://bwmarrin.github.io/MkDocsPlus/fontawesome/

Thanks for the great extension and again - sorry for the horribly slow response.

**Comment by bmcorser** [comment]
@bwmarrin I'm assuming this is addressed by @HWataru's PR `:)`
